### ISSUE TITLE
Remove email addresses from footer

### ISSUE THREAD

**Issue by Awfulnaut** [brijamfitz/Recca#31]

**Comment by Ekeyes8500** [comment]
Change to javascript addition of email addresses instead

**Comment by Awfulnaut** [comment]
Anthony recommended using nodemailer:
https://codeburst.io/sending-an-email-using-nodemailer-gmail-7cfa0712a799
https://stackoverflow.com/questions/23002711/how-to-show-email-addresses-on-the-website-to-avoid-spams

Or we could just provide the email addresses using javascript

**Comment by Awfulnaut** [comment]
Fix applied to develop. I'm going to create a new ticket for creating a contact form, as that would ultimately be better.
