### ISSUE TITLE
Create more efficient feed db call 

### ISSUE THREAD

**Issue by Ekeyes8500** [brijamfitz/Recca#38]
Current call does each feed object individual, will create by user

**Comment by Ekeyes8500** [comment]
Non-issue due to loading recca

**Comment by Awfulnaut** [comment]
I'm reopening this since it takes 10+ seconds to load, even when you click away and then back to /home... @Ekeyes8500 I'm assigning it both of us since I'm willing to take a look at this when I knock out my other bugs.

**Comment by Ekeyes8500** [comment]
updated to pull by user instead of by post
